apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    labels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
      rbac.authorization.k8x.io/aggregate-to-edit: "true"
    name: aggregate-iprangedefinition-admin-edit
  rules:
  - apiGroups:
    - openpaas.com
    resources:
    - iprangedefinitions
    verbs:
    - get
    - list
    - watch
    - delete
    - create
    - update
    - patch
    - delletecollection
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    labels:
      rbac.authorization.k8x.io/aggregate-to-view: "true"
    name: aggregate-iprangedefinition-view
  rules:
  - apiGroups:
    - openpaas.com
    resources:
    - iprangedefinitions
    verbs:
    - get
    - list
    - watch
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
