apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iprangedefinitions.openpaas.com
spec:
  additionalPrinterColumns:
  group: openpaas.com
  names:
    kind: IPRangeDefinition
    listKind: IPRangeDefinitionList
    plural: iprangedefinitions
    shortNames:
    - iprd
    - iprds
    singular: iprangedefinition
  scope: Namespaced
  validation:
    subresources:
      status: {}
    openAPIV3Schema:
      preserveUnknownField: false
      type: object
      required: [ spec ]
      properties:
        spec:
          type: object
          required:  [ cidrs ]
          properties:
            cidrs:
              type: array
              items:
                type: string
        status:
          type: object
          properties:
            hash:
              type: string
            info:
              type: string
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
